name: Build static Debian package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
      
    - id: get_version
      uses: battila7/get-version-action@v2
    
    - name: build x86_64-unknown-linux-musl
      uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
      
    - name: Upload Debian package as artifact
      id: upload-debfile 
      uses: actions/upload-artifact@v3
      with:
        path: target/x86_64-unknown-linux-musl/debian/mactime2_${{ steps.get_version.outputs.version-without-v }}_amd64.deb
        name: mactime2_${{ steps.get_version.outputs.version-without-v }}_amd64.deb
