name: Build static Debian package
on:
  # push:
  #   # Sequence of patterns matched against refs/tags
  #   tags:
  #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  - workflow_run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
      
    - id: get_version
      uses: battila7/get-version-action@v2
    
    - name: build x86_64-unknown-linux-musl
      uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
      
    - name: Upload Release Asset
      id: upload-debfile 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/x86_64-unknown-linux-musl/debian/mactime2_${{ steps.get_version.outputs.version }}_amd64.deb
        asset_name: mactime2_${{ steps.get_version.outputs.version }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package
