name: Deb Static Build

on: 
  - release
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      
    - id: get_version
      uses: battila7/get-version-action@v2
    
    - name: build x86_64-unknown-linux-musl
      uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
      
    - name: Upload Release Asset
      id: upload-debfile 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./target/x86_64-unknown-linux-musl/debian/mactime2_${{ steps.get_version.outputs.version }}.deb
        asset_name: mactime2_${{ steps.get_version.outputs.version }}.deb
        asset_content_type: application/vnd.debian.binary-package
